name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/prachwal/index.json
      env:
        NUGET_AUTH_TOKEN: '%PUBLISH_TO_GITHUB_COM%'
    - name: Install dependencies
      run: dotnet restore
      env:
        PUBLISH_TO_GITHUB_COM: ${{ secrets.GH_TOKEN }}
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Test Add source
      run: dotnet nuget --help
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish the package to GPR
      run: dotnet nuget push "app/bin/Release/*.nupkg" --skip-duplicate
        dotnet nuget push "tool/bin/Release/*.nupkg" --skip-duplicate
      env:
        PUBLISH_TO_GITHUB_COM: ${{ secrets.GH_TOKEN }}
